services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting container node_modules with local
      - /app/.git  # exclude .git directory
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: sh -c "bun generate && bun migrate && bun seed && bun run dev"
#    bun remove openai && rm -rf ~/.bun/install/cache && bun add openai@latest
    depends_on:
      qdrant:
        condition: service_healthy
    
  qdrant:
    image: qdrant/qdrant:v1.12.5
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      QDRANT__SERVICE__API_KEY: Junior-Ferocity5-Antsy
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  sqlite-data: